version: '3.3'
services:

  carreiras_db:
    image: 'mariadb:10.5.9'
    container_name: carreiras_db
    volumes:
      - './mysql:/var/lib/mysql'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_USER: 'root'
      MYSQL_DATABASE: 'carreiras'
      MYSQL_ROOT_PASSWORD: 'root'

  carreiras_web:
    image: wordpress:php8.0
    container_name: carreiras_web
    ports:
      - '80:80'
    links:
      - carreiras_db
    volumes:
      - './app:/var/www/html'
    environment:
      WEB_DOCUMENT_ROOT: /var/www/html

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: carreiras_phpmyadmin
    environment:
      PMA_HOST: carreiras_db
    ports:
      - 8080:80
    depends_on:
      - carreiras_db
    restart: always